### ISSUE TITLE
Crashes when I try to play a track (Error reading the stream. (code 18) (StandardError))

### ISSUE THREAD

**Issue by eramdam** [grobie/soundcloud2000#53]
OSX 10.9.3, ruby 2.0.0p247 (using rbenv/ruby-build installed on Homebrew)

I found the debug log 

``` bash
Warning: Xing stream size off by more than 1%, fuzzy seeking may be even more fuzzy than by design!
/usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/models/player.rb:51:in `new': Error reading the stream. (code 18) (StandardError)
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/models/player.rb:51:in `length_in_seconds'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/models/player.rb:58:in `load'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/models/player.rb:34:in `play'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/controllers/player_controller.rb:61:in `play'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/application.rb:38:in `block in initialize'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/events.rb:13:in `call'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/events.rb:13:in `block in trigger'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/events.rb:12:in `each'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/events.rb:12:in `trigger'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/controllers/track_controller.rb:21:in `block in initialize'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/events.rb:13:in `call'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/events.rb:13:in `block in trigger'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/events.rb:12:in `each'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/events.rb:12:in `trigger'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/application.rb:74:in `handle'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/application.rb:49:in `block in main'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/application.rb:47:in `loop'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/application.rb:47:in `main'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/application.rb:65:in `run'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000.rb:15:in `start'
        from /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/soundcloud2000-0.1.0/bin/soundcloud2000:5:in `<top (required)>'
        from /usr/local/var/rbenv/versions/2.0.0-p247/bin/soundcloud2000:23:in `load'
        from /usr/local/var/rbenv/versions/2.0.0-p247/bin/soundcloud2000:23:in `<main>'
```

**Comment by JahBrewski** [comment]
Just found this app today and love the idea! Unfortunately as-is it is quite unstable and prone to crashing. Looks like it isn't under active development anymore? Perhaps I could help out?
