### ISSUE TITLE
portaudio/mpg123 issue when running soundcloud2000

### ISSUE THREAD

**Issue by jkleve** [grobie/soundcloud2000#96]
I was able to install soundcloud2000 on Korora 24 (Fedora) but when I try to run it I get the following error

```
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in 'require': /home/jesse/.gem/ruby/extensions/x86_64-linux/2.3.0/audite-0.4.0/portaudio.so: undefined symbol: mpg123_plain_strerror - /home/jesse/.gem/ruby/extensions/x86_64-linux/2.3.0/audite-0.4.0/portaudio.so (LoadError)
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in 'require'
    from /home/jesse/.gem/ruby/gems/audite-0.4.0/lib/audite.rb:1:in '<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in 'require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in 'require'
    from /home/jesse/.gem/ruby/gems/soundcloud2000-0.1.0/lib/soundcloud2000/models/player.rb:1:in '<top (required)>'
    from /home/jesse/.gem/ruby/gems/soundcloud2000-0.1.0/lib/soundcloud2000/controllers/player_controller.rb:2:in 'require_relative'
    from /home/jesse/.gem/ruby/gems/soundcloud2000-0.1.0/lib/soundcloud2000/controllers/player_controller.rb:2:in '<top (required)>'
    from /home/jesse/.gem/ruby/gems/soundcloud2000-0.1.0/lib/soundcloud2000/application.rb:8:in 'require_relative'
    from /home/jesse/.gem/ruby/gems/soundcloud2000-0.1.0/lib/soundcloud2000/application.rb:8:in '<top (required)>'
    from /home/jesse/.gem/ruby/gems/soundcloud2000-0.1.0/lib/soundcloud2000.rb:2:in 'require_relative'
    from /home/jesse/.gem/ruby/gems/soundcloud2000-0.1.0/lib/soundcloud2000.rb:2:in '<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in 'require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in 'require'
    from /home/jesse/.gem/ruby/gems/soundcloud2000-0.1.0/bin/soundcloud2000:3:in '<top (required)>'
    from /home/jesse/bin/soundcloud2000:23:in 'load'
    from /home/jesse/bin/soundcloud2000:23:in '<main>'
```

**Comment by grobie** [comment]
To be honest, since I switched back to Linux a few years ago, I've never been able to run soundcloud200 again. I'm open for any kind of fixes.

**Comment by Francesco149** [comment]
for anyone still interested in running this, for whatever reason ruby doesn't link audite against -lmpg123, this can be fixed by ```gem uninstall audite``` and reinstalling with the proper flags: ```gem install --user audite -- --with-ldflags="-lmpg123"```

after that the client worked just fine for me

**Comment by ZaxonXP** [comment]
@Francesco149: You saved my day. :)
