### ISSUE TITLE
not working on mac

### ISSUE THREAD

**Issue by kikieri** [grobie/soundcloud2000#98]
when I want to start it got this:

/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- curses (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/ui/canvas.rb:1:in `<top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/application.rb:3:in `require_relative'
	from /Library/Ruby/Gems/2.3.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/application.rb:3:in `<top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000.rb:2:in `require_relative'
	from /Library/Ruby/Gems/2.3.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/soundcloud2000-0.1.0/bin/soundcloud2000:3:in `<top (required)>'
	from /usr/local/bin/soundcloud2000:22:in `load'
	from /usr/local/bin/soundcloud2000:22:in `<main>'

**Comment by tworeimage** [comment]
@kikieri you need to do `gem install curses` and the binary should work after that
