### ISSUE TITLE
Error on Debian 10

### ISSUE THREAD

**Issue by ZaxonXP** [grobie/soundcloud2000#99]
Tried to install as the readme instructed, but when executing got such error:
```
Traceback (most recent call last):
        11: from /usr/local/bin/soundcloud2000:23:in `<main>'
        10: from /usr/local/bin/soundcloud2000:23:in `load'
         9: from /var/lib/gems/2.5.0/gems/soundcloud2000-0.1.0/bin/soundcloud2000:3:in `<top (required)>'
         8: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         6: from /var/lib/gems/2.5.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000.rb:2:in `<top (required)>'
         5: from /var/lib/gems/2.5.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000.rb:2:in `require_relative'
         4: from /var/lib/gems/2.5.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/application.rb:3:in `<top (required)>'
         3: from /var/lib/gems/2.5.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/application.rb:3:in `require_relative'
         2: from /var/lib/gems/2.5.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/ui/canvas.rb:1:in `<top (required)>'
         1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- curses (LoadError)
```

**Comment by VP1147** [comment]
Same problem here. Solved installing package _ruby-curses_.

**Comment by ZaxonXP** [comment]
@VP1147: Thanks for the hint. Now I am getting another error:
```
Traceback (most recent call last):
        16: from /usr/local/bin/soundcloud2000:23:in `<main>'
        15: from /usr/local/bin/soundcloud2000:23:in `load'
        14: from /var/lib/gems/2.5.0/gems/soundcloud2000-0.1.0/bin/soundcloud2000:3:in `<top (required)>'
        13: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        12: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        11: from /var/lib/gems/2.5.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000.rb:2:in `<top (required)>'
        10: from /var/lib/gems/2.5.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000.rb:2:in `require_relative'
         9: from /var/lib/gems/2.5.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/application.rb:8:in `<top (required)>'
         8: from /var/lib/gems/2.5.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/application.rb:8:in `require_relative'
         7: from /var/lib/gems/2.5.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/controllers/player_controller.rb:2:in `<top (required)>'
         6: from /var/lib/gems/2.5.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/controllers/player_controller.rb:2:in `require_relative'
         5: from /var/lib/gems/2.5.0/gems/soundcloud2000-0.1.0/lib/soundcloud2000/models/player.rb:1:in `<top (required)>'
         4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         2: from /var/lib/gems/2.5.0/gems/audite-0.4.0/lib/audite.rb:1:in `<top (required)>'
         1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': /var/lib/gems/2.5.0/gems/audite-0.4.0/lib/portaudio.so: undefined symbol: mpg123_read - /var/lib/gems/2.5.0/gems/audite-0.4.0/lib/portaudio.so (LoadError)
```
What do I miss now?

**Comment by ZaxonXP** [comment]
OK. I found that I need to do what is described in the #96:
```
sudo gem uninstall audite
sudo gem install audite -- --with-ldflags="-lmpg123"
```
